In [2]:
import pandas as pd
from functools import reduce

pd.options.display.float_format = '{:.5f}'.format #e 나오는거 싫어서 바꿈

df = pd.read_excel('../2020/20년도_1월_CO오염도.xlsx')
df
# df = df.drop([0,2,3])
# df = df.iloc[:, 0:9]
# df = df.rename(columns=df.iloc[0])
# df = df.drop([1])
# df = df.drop([415, 416])
# df_seoul = df[df['시.도'] == '서울']
# df_gg = df[df['시.도'] == '경기']
# df_incheon = df[df['시.도'] == '인천']
# df_daegu = df[df['시.도'] == '대구']

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,- CO 오염도,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,시.도,시군구,측정소명,측정소\n코드,유효\n자료\n획득률\n(%),유효\n측정\n일수\n(day),유효\n측정\n횟수\n(8hour),유효\n측정\n시간\n(hour),월평균\n(ppm),1시간치,NaN,NaN,NaN,NaN,8시간치,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,최저\n(ppm),최고\n(ppm),최고일시,기준초과\n(회),초과율\n(%),최저\n(ppm),최고\n(ppm),최고일시,기준초과\n(회),초과율\n(%)
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,서울,중구,중구,111121,99.46,31,744,740,0.7,0.3,1.5,2020012309,NaN,NaN,0.3,1.3,202001040512,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,제주,서귀포,성산읍,339122,99.32,31,738,739,0.3,0.1,0.7,2020010410,NaN,NaN,0.2,0.6,202001040512,NaN,NaN
413,제주,서귀포,대정읍,339131,99.46,31,744,740,0.3,0.1,0.7,2020010412,NaN,NaN,0.2,0.6,202001190613,NaN,NaN
414,제주,서귀포,남원읍,339123,99.59,31,744,741,0.3,0.1,0.7,2020011915,NaN,NaN,0.2,0.6,202001190916,NaN,NaN
415,"* ""농도값*""의 값은 자료 획득률이 50% 이상이나 75% 미만인 도시의 월평...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"* ""농도값**""의 값은 자료 획득률이 50% 미만인 도시의 월평균 값임.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
416,* 충북 용담동 측정소는 측정소 이전으로 인한 가동중지.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN